# This is a basic workflow to help you get started with Actions

name: Building Extension

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Build-Pipeline-Ubuntu:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: NPM Package Installation
        run: npm install
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  Build-Pipeline-Windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: NPM Package Installation
          run: npm install
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
          
  Build-Pipeline-MacOS:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: NPM Package Installation
          run: npm install
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
