# This is a basic workflow to help you get started with Actions

name: Building Extension

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Build-Pipeline-Ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: NPM Package Installation
        run: npm install
      - name: Build
        run: npm run compile
      - name: Setup Display Var
        run: sudo apt-get install xvfb
      - name: T  
        run: xvfb-run --auto-servernum npm test
      - name: Run Test
        run: yarn test
    
  Build-Pipeline-Ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: NPM Package Installation
        run: npm install
      - name: Build
        run: npm run compile
      - name: Run Test
        run: npm test
          
  Build-Pipeline-Ubuntu-16:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: NPM Package Installation
        run: npm install
      - name: Build
        run: npm run compile
      - name: Run Test
        run: npm test

  Build-Pipeline-Windows-2019:
      runs-on: windows-2019
      steps:
        - uses: actions/checkout@v2
        - name: NPM Package Installation
          run: npm install
        - name: Build
          run: npm run compile
        - name: Run Test
          run: npm test
  
  Build-Pipeline-Windows-2016:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: NPM Package Installation
        run: npm install
      - name: Build
        run: npm run compile
      - name: Run Test
        run: npm test

  Build-Pipeline-MacOS-10:
      runs-on: macos-10.15
      steps:
        - uses: actions/checkout@v2
        - name: NPM Package Installation
          run: npm install
        - name: Build
          run: npm run compile
        - name: Run Test
          run: npm test
